# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iD15g-59qBHI-B60UXKfsAqg7CKNfqUX

Receber um número de tabuadas para imprimir por linha, número por onde vai começar a tabuada e o que vai terminar.
"""

def buildTable(actualNumber):
    results = []
    for multiplication in range(1,11):
        results.append(f'{actualNumber} * {multiplication} = {actualNumber * multiplication}')
    return results    

def buildTables(start,end):
    tables = []
    for actualNumber in range(start, end+1):
        tables.append(buildTable(actualNumber))
    return tables

start = int(input("Qual a tabuada inicial?"))
end = int(input("Qual a tabuada final?"))
quantTable = int(input("Quantas tabuadas você quer imprimir por linha?"))

tables = buildTables(start,end)
print(tables)
#printTables(quantTable, tables)